// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXjx8ItyRnpoyEVrwMTiRGkubtzFF_8o8',
    appId: '1:444097780030:web:60aedbb1dc16420afa346f',
    messagingSenderId: '444097780030',
    projectId: 'workout-tracker-fa617',
    authDomain: 'workout-tracker-fa617.firebaseapp.com',
    storageBucket: 'workout-tracker-fa617.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwwJ-MFxwwoQieyRyENH_8KYbC3NazWSs',
    appId: '1:444097780030:android:dc16ac085f32a2c8fa346f',
    messagingSenderId: '444097780030',
    projectId: 'workout-tracker-fa617',
    storageBucket: 'workout-tracker-fa617.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnsAnm4_iWS3dYVivu9mFsb47mJWzMbDA',
    appId: '1:444097780030:ios:103992d8e9ad21f0fa346f',
    messagingSenderId: '444097780030',
    projectId: 'workout-tracker-fa617',
    storageBucket: 'workout-tracker-fa617.firebasestorage.app',
    iosBundleId: 'com.example.workoutTrackerApp',
  );
}
